# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: hydrodaten_development

test:
  <<: *default
  database: hydrodaten_test

staging:
 <<: *default
 url: <%= ENV['DATABASE_URL'] %>
 database: hydrodaten_production

production:
  <<: *default
  database: hydrodaten_production
  username: rails
  password: involve_bursa_inimical_hinder_linear
