# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: hydrodaten_development


test:
  <<: *default
  database: hydrodaten_test

production:
  <<: *default
  database: hydrodaten_production
