# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8d25de0a732eb14d7ba9afb9bda44cdcf4f314bd65734d865b900ee86ffa5a07082b03059562d892f9172e7d364644a3f818d783b6c44972df537d6a3437a58
  HYDRODATA_USERNAME: 'funternaehrer'
  HYDRODATA_PASSWORD: 'okoum49.bill'

test:
  secret_key_base: 3503a06528f801252010d9fc58b47ab92ae0991647f9f4fa434de0af9ac4549c06559e32a8f4bfa471c1c7f45c69cdcf83683e719b9df1f3bebfbe95edc3cdf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d8353e999c77e9c3658e21d050d116b93a9619b04f64924ac0b46b1d768520bb1dae7fbd5a61df9828933abbbd757b52b025e6753e127c89a5f29ca6d66deb7b

