# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7702c9746d5e5ab002c3d9f246086ebab98049817fd66e31b885de5dd048661ec3f1ff2119d664d6d09d88ad372233f26d232b789fd16a25027ce05aaedfdb7
  HYDRODATA_USERNAME: 'funternaehrer'
  HYDRODATA_PASSWORD: <%= ENV['HYDRODATA_PASSWORD'] %>

test:
  secret_key_base: bd2f2f68f2ec81f28dca4158b5a602d6c91a19fa6f57127f2598d6a9ddd66680c1f024951f2be6642ae96fce31e1d46ac1aedb5fbcad8749277998aae574d12d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['APP_SECRET'] %>

